name: polylingo
description: A language learning app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: 5.5.0
  crypto: ^3.0.1
  fluttertoast: ^8.2.1
  http: ^1.2.2
  translator: ^1.0.3

  #carousel_slider: ^4.1.0

flutter:
  assets:
    - assets/japan_flag.png
    - assets/us_flag.png
    - assets/spain_flag.png
    - assets/image1.jpg
    - assets/image2.jpg
    - assets/image3.jpg
    - assets/image4.jpg
    - assets/image5.jpg
    - assets/image6.jpg
  uses-material-design: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

